# M5 Pro baseline generated from the 2026-09-30 Intel Mac inventory.
# Homebrew installs Apple Silicon builds from /opt/homebrew on the new Mac.

tap "hashicorp/tap"

# Core command-line and development tools
brew "aircrack-ng"
brew "ansible"
brew "awscli"
brew "cmake"
brew "exiftool"
brew "ffmpeg"
brew "ffuf"
brew "git"
brew "gnupg"
brew "go"
brew "httrack"
brew "knock"
brew "make"
brew "mas"
brew "netcat"
brew "nmap"
brew "node"
brew "p7zip"
brew "powershell"
brew "pwncat"
brew "python@3.13"
brew "rtl_433"
brew "rust"
brew "testdisk"
brew "tree"
brew "uv"
brew "watch"
brew "wget"

# HashiCorp tools used on the Intel Mac
brew "hashicorp/tap/consul", trusted: true
brew "hashicorp/tap/packer", trusted: true
brew "hashicorp/tap/terraform", trusted: true
brew "hashicorp/tap/vault", trusted: true

# Daily applications with current Apple Silicon or universal packages
cask "aerial"
cask "balenaetcher"
cask "brave-browser"
cask "claude"
cask "claude-code"
cask "discord"
cask "docker-desktop"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "keepassxc"
cask "maccy"
cask "microsoft-teams"
cask "mqtt-explorer"
cask "obs"
cask "onedrive"
cask "raspberry-pi-imager"
cask "reolink"
cask "ringcentral"
cask "signal"
cask "slack"
cask "spotify"
cask "tailscale-app"
cask "teamviewer"
cask "tunnelblick"
cask "visual-studio-code"
cask "webex"
cask "wireshark-app"
cask "xquartz"
cask "yubico-authenticator"
cask "zoom"

# Curated VS Code extensions from the current Mac
vscode "docker.docker"
vscode "esbenp.prettier-vscode"
vscode "github.vscode-pull-request-github"
vscode "google.geminicodeassist"
vscode "googlecloudtools.cloudcode"
vscode "hashicorp.terraform"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.powershell"
vscode "openai.chatgpt"
vscode "platformio.platformio-ide"
vscode "redhat.ansible"
vscode "redhat.vscode-xml"
