---
- name: Configure this Mac
  hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:
    - name: Verify macOS
      ansible.builtin.assert:
        that:
          - ansible_system == 'Darwin'
        fail_msg: This playbook supports macOS only.
      tags:
        - always

  roles:
    - role: homebrew
      tags:
        - homebrew
        - applications

    - role: shell
      tags:
        - shell

    - role: powershell
      tags:
        - development
        - powershell
