---
# Legacy task retained during migration.

- name: Application installs
  ansible.builtin.include_tasks: homebrew.yml

- name: Getting downloads
  ansible.builtin.get_url:
    url: "{{ item.value.url }}"
    dest: "{{ item.value.dest }}"
    mode: "0644"
  loop: "{{ downloads | dict2items }}"

- name: Install Homebrew formulae
  community.general.homebrew:
    name: "{{ applications }}"
    state: present

- name: Install Homebrew cask applications
  community.general.homebrew_cask:
    name: "{{ cask_applications }}"
    state: present
