---
- name: Application installs
  ansible.builtin.include_tasks: apps.yml

- name: Configuration
  ansible.builtin.include_tasks: configuration.yml

- name: Dotfiles
  ansible.builtin.include_tasks: dotfiles.yml
